name: Deploy release directly to Cloud Platform

on:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    name: 'Validate'
    uses: ./.github/workflows/validation.yml
    secrets: inherit

  image:
    name: 'Build & Push Image'
    uses: ./.github/workflows/build-push-image.yml
    needs: [validate]
    secrets: inherit

  deploy_development:
    name: 'Deploy to Development'
    uses: ./.github/workflows/deploy.yml
    needs: [image, validate]
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit
